const regions={utc:{name:'UTC',country:'Monde',tz:'UTC'},paris:{name:'Paris',country:'France',tz:'Europe/Paris'},london:{name:'Londres',country:'Royaume-Uni',tz:'Europe/London'},newyork:{name:'New York',country:'États-Unis',tz:'America/New_York'},losangeles:{name:'Los Angeles',country:'États-Unis',tz:'America/Los_Angeles'},mexico:{name:'Mexico',country:'Mexique',tz:'America/Mexico_City'},saopaulo:{name:'São Paulo',country:'Brésil',tz:'America/Sao_Paulo'},cairo:{name:'Le Caire',country:'Égypte',tz:'Africa/Cairo'},johannesburg:{name:'Johannesburg',country:'Afrique du Sud',tz:'Africa/Johannesburg'},dubai:{name:'Dubai',country:'Émirats',tz:'Asia/Dubai'},mumbai:{name:'Mumbai',country:'Inde',tz:'Asia/Kolkata'},singapore:{name:'Singapore',country:'Singapour',tz:'Asia/Singapore'},tokyo:{name:'Tokyo',country:'Japon',tz:'Asia/Tokyo'},seoul:{name:'Séoul',country:'Corée du Sud',tz:'Asia/Seoul'},shanghai:{name:'Shanghai',country:'Chine',tz:'Asia/Shanghai'},sydney:{name:'Sydney',country:'Australie',tz:'Australia/Sydney'},auckland:{name:'Auckland',country:'Nouvelle-Zélande',tz:'Pacific/Auckland'}};
const key=document.body.dataset.clock||'utc',region=regions[key]||regions.utc,canvas=document.querySelector('#clock'),ctx=canvas.getContext('2d');document.querySelector('#name').textContent=region.name;document.querySelector('#country').textContent=region.country;document.title=`ViA — ${region.name}`;
function parts(date){const m={};new Intl.DateTimeFormat('en-US',{timeZone:region.tz,hour12:false,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',fractionalSecondDigits:3}).formatToParts(date).forEach(x=>m[x.type]=x.value);return{y:+m.year,mo:+m.month,d:+m.day,h:+m.hour,mi:+m.minute,s:+m.second,ms:+(m.fractionalSecond||0)}}
function text(v,x,y,color,size){ctx.fillStyle=color;ctx.font=`600 ${size}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(v,x,y)}
function ring(x,y,radius,start,end,width,color,alpha=1){ctx.beginPath();ctx.arc(x,y,radius,start,end);ctx.lineWidth=width;ctx.strokeStyle=color;ctx.globalAlpha=alpha;ctx.stroke();ctx.globalAlpha=1}
function draw(p){const b=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=b.width*d;canvas.height=b.height*d;ctx.setTransform(d,0,0,d,0,0);const x=b.width/2,y=b.height/2,R=Math.min(b.width,b.height)*.36;ctx.clearRect(0,0,b.width,b.height);ctx.globalCompositeOperation='lighter';
// Photoplasma : un pointeur laser dont chaque unité temporelle possède sa couleur et son anneau.
const colors={ms:'#ff79c6',s:'#ff5267',m:'#ffd34e',h:'#55e7cf',d:'#70baff',mo:'#a98cff',y:'#ffffff'};
const secProgress=(p.s+p.ms/1000)/60,minuteProgress=(p.mi+secProgress)/60,hourProgress=(p.h%24+minuteProgress)/24;
const bubbles=[{r:R*.18+R*.18*(p.ms/1000),color:colors.ms},{r:R*.34+R*.16*secProgress,color:colors.s},{r:R*.52+R*.15*minuteProgress,color:colors.m},{r:R*.70+R*.13*hourProgress,color:colors.h},{r:R*.86+R*.10*(p.d/31),color:colors.d}];
for(const bbl of bubbles){ctx.beginPath();ctx.arc(x,y,bbl.r,0,Math.PI*2);ctx.lineWidth=1.5;ctx.strokeStyle=bbl.color;ctx.globalAlpha=.18;ctx.stroke();ctx.globalAlpha=1}
// Millisecondes : le rayon photoplasma pulse à chaque milliseconde.
const phase=-Math.PI/2+secProgress*Math.PI*2;const laserStart=-Math.PI/2;const plasmaR=R*(.20+.72*hourProgress);ring(x,y,plasmaR,laserStart,phase,5,colors.ms,.9);ring(x,y,plasmaR+8,laserStart,phase,2,colors.s,.55);
// 60 anneaux fins de secondes : l'anneau courant se ferme progressivement.
for(let n=1;n<=60;n++){const r=R*(.22+n*.008),a=-Math.PI/2+n*Math.PI*2/60,active=n===p.s+1;ring(x,y,r,active?-Math.PI/2:-.025+a,a,active?2.5:1.1,colors.s,active?.95:.22);if(n%5===0)text(n,x+Math.cos(a)*r,y+Math.sin(a)*r,colors.s,9)}
// 60 anneaux de minutes, plus épais, chacun alimenté par une vague jaune.
for(let n=1;n<=60;n++){const r=R*(.62+n*.004),a=-Math.PI/2+n*Math.PI*2/60,active=n===p.mi+1;ring(x,y,r,active?-Math.PI/2:-.035+a,a,active?4:2.2,colors.m,active?.95:.3);if(n%5===0)text(n,x+Math.cos(a)*r,y+Math.sin(a)*r,colors.m,9)}
// 24 anneaux verts d'heures, puis jour, mois et année en couches externes.
for(let n=1;n<=24;n++){const a=-Math.PI/2+n*Math.PI*2/24,r=R*1.02;ring(x,y,r,a-.045,a+.045,3,colors.h,.25+(n<=p.h?'.35':0));text(n,x+Math.cos(a)*r,y+Math.sin(a)*r,colors.h,10)}
ring(x,y,R*1.13,-Math.PI/2,-Math.PI/2+Math.PI*2*(p.d/31),3,colors.d,.8);ring(x,y,R*1.22,-Math.PI/2,-Math.PI/2+Math.PI*2*(p.mo/12),4,colors.mo,.75);ring(x,y,R*1.31,-Math.PI/2,-Math.PI/2+Math.PI*2*((p.y%100)/100),5,colors.y,.7);
// Pointeur photoplasma en forme de vague : sa tête indique l'instant UTC/local.
ctx.beginPath();for(let i=0;i<=100;i++){const t=i/100,angle=phase-t*2.8,rad=plasmaR*t*(.35+.65*t),xx=x+Math.cos(angle)*rad,yy=y+Math.sin(angle)*rad;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)}ctx.lineWidth=7;ctx.lineCap='round';ctx.strokeStyle=colors.s;ctx.shadowBlur=24;ctx.shadowColor=colors.s;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=colors.ms;ctx.beginPath();ctx.arc(x+Math.cos(phase)*plasmaR,y+Math.sin(phase)*plasmaR,8,0,Math.PI*2);ctx.fill();ctx.globalCompositeOperation='source-over'}
function update(){const now=new Date(),p=parts(now);document.querySelector('#time').textContent=`${String(p.h).padStart(2,'0')}:${String(p.mi).padStart(2,'0')}:${String(p.s).padStart(2,'0')}.${String(p.ms).padStart(3,'0')}`;document.querySelector('#date').textContent=new Intl.DateTimeFormat(document.documentElement.lang||'fr',{timeZone:region.tz,dateStyle:'full'}).format(now);draw(p)}document.querySelector('#back').onclick=()=>location.href='index.html';document.querySelector('#coff').onclick=()=>location.href='coff.html';update();setInterval(update,50);addEventListener('resize',update);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
